#include "source/sprites/sprite_definitions.h"

// NOTE: All of this data is in the primary bank.

// Put all newly-designed sprites here. 8 Bytes per sprite, defined mostly from constants
// in sprite_definitions.h. The 8 bytes are: 
// 1st byte: Sprite type 
// 2nd byte: Tile id for first tile, using 8x8 grid. See the guide for more detail on this.
// 3rd byte: Split; contains sprite size and palette. Combine the constants
//           using the logical OR operator (represented by the bar character: |) 
// 4th byte: Animation type
// 5th byte: How the sprite moves.
// 6th-8th byte: Miscellaneous; you can use this for whatever extra data you need. For enemies, byte 5
//           is used as the damage they deal. Health powerups use byte 5 to store how much to restore. 
//           Byte 6 is used for movement speed on enemies and npcs.
//           Byte 7 is used for health on enemy sprites in our `add_sword` branch.
// NOTE: This array cannot contain more than 64 sprites, or other logic will break.
const unsigned char spriteDefinitions[] = {
    // Madman
    SPRITE_TYPE_REGULAR_ENEMY, 0x08, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_LEFT_RIGHT, 0x20, 0x00, DIM_SPRITE_ID_MADMAN,
    SPRITE_TYPE_REGULAR_ENEMY, 0x08, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_UP_DOWN, 0x20, 0x00, DIM_SPRITE_ID_MADMAN,
    SPRITE_TYPE_REGULAR_ENEMY, 0x08, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_RANDOM_WANDER, 0x20, 0x00, DIM_SPRITE_ID_MADMAN,
    SPRITE_TYPE_GEM, 0xca, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_NONE, SPRITE_MOVEMENT_NONE, 0x00, 0x00, 0x00,
    SPRITE_TYPE_INVULNERABLE_ENEMY, 0xcc, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_SWAP, SPRITE_MOVEMENT_LEFT_RIGHT, -60, 0x00, 0x01,
    SPRITE_TYPE_INVULNERABLE_ENEMY, 0xcc, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_3, SPRITE_ANIMATION_SWAP, SPRITE_MOVEMENT_UP_DOWN, -60, 0x00, 0x01,
    SPRITE_TYPE_DOOR, 0xce, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_0, SPRITE_ANIMATION_NONE, SPRITE_MOVEMENT_NONE, 0x00, 0x00, 0x00,
    SPRITE_TYPE_LOCKED_DOOR, 0xc8, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_0, SPRITE_ANIMATION_NONE, SPRITE_MOVEMENT_NONE, 0x00, 0x00, 0x00,
    SPRITE_TYPE_ENDGAME, 0xc6, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_NONE, SPRITE_MOVEMENT_NONE, 0x00, 0x00, 0x00,
    SPRITE_TYPE_NPC, 0x00, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_NONE, SPRITE_MOVEMENT_NONE, 0x01, 14, 0x00,
    
    // Transitions - 3rd to last is dimension 1, 2nd to last is dimension 2, last is unused
    SPRITE_TYPE_TRANSITION, 0x48, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_0, SPRITE_ANIMATION_SWAP, SPRITE_MOVEMENT_NONE, 0x00, 0x01, 0x00,
    SPRITE_TYPE_TRANSITION, 0x48, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_0, SPRITE_ANIMATION_SWAP, SPRITE_MOVEMENT_NONE, 0x00, 0x02, 0x00,
    SPRITE_TYPE_TRANSITION, 0x48, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_0, SPRITE_ANIMATION_SWAP, SPRITE_MOVEMENT_NONE, 0x02, 0x03, 0x00,
    SPRITE_TYPE_TRANSITION, 0x48, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_0, SPRITE_ANIMATION_SWAP, SPRITE_MOVEMENT_NONE, 0x03, 0x04, 0x00,
    SPRITE_TYPE_TRANSITION, 0x48, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_0, SPRITE_ANIMATION_SWAP, SPRITE_MOVEMENT_NONE, 0x04, 0x05, 0x00,
    // NOTE: If index changed (currently 15) constant needs a change
    SPRITE_TYPE_TRANSITION, 0x48, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_0, SPRITE_ANIMATION_SWAP, SPRITE_MOVEMENT_NONE, 0x05, 0x00, 0xff, // THAT LAST VALUE IS IMPORTANT! NO TOUCHY!

    // Blue ball enemy
    SPRITE_TYPE_REGULAR_ENEMY, 0x88, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_LEFT_RIGHT, 0x20, 0x00, DIM_SPRITE_ID_BLUEBALL,
    SPRITE_TYPE_REGULAR_ENEMY, 0x88, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_UP_DOWN, 0x20, 0x00, DIM_SPRITE_ID_BLUEBALL,
    SPRITE_TYPE_REGULAR_ENEMY, 0x88, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_RANDOM_WANDER, 0x20, 0x00, DIM_SPRITE_ID_BLUEBALL,

    // Red ball
    SPRITE_TYPE_REGULAR_ENEMY, 0x88, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_LEFT_RIGHT, 0x20, 0x00, DIM_SPRITE_ID_REDBALL,
    SPRITE_TYPE_REGULAR_ENEMY, 0x88, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_UP_DOWN, 0x20, 0x00, DIM_SPRITE_ID_REDBALL,
    SPRITE_TYPE_REGULAR_ENEMY, 0x88, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_RANDOM_WANDER, 0x20, 0x00, DIM_SPRITE_ID_REDBALL,

    // Volcano
    SPRITE_TYPE_REGULAR_ENEMY, 0x40, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_LEFT_RIGHT, 0x20, 0x00, DIM_SPRITE_ID_VOLCANO,
    SPRITE_TYPE_REGULAR_ENEMY, 0x40, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_UP_DOWN, 0x20, 0x00, DIM_SPRITE_ID_VOLCANO,
    SPRITE_TYPE_REGULAR_ENEMY, 0x40, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_2, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_RANDOM_WANDER, 0x20, 0x00, DIM_SPRITE_ID_VOLCANO,

    // Time cop
    SPRITE_TYPE_REGULAR_ENEMY, 0x00, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_LEFT_RIGHT, 0x20, 0x00, DIM_SPRITE_ID_TIMECOP,
    SPRITE_TYPE_REGULAR_ENEMY, 0x00, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_UP_DOWN, 0x20, 0x00, DIM_SPRITE_ID_TIMECOP,
    SPRITE_TYPE_REGULAR_ENEMY, 0x00, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_1, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_RANDOM_WANDER, 0x20, 0x00, DIM_SPRITE_ID_TIMECOP,

    // Hyper timecop
    SPRITE_TYPE_REGULAR_ENEMY, 0x00, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_3, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_LEFT_RIGHT, 0x20, 0x00, DIM_SPRITE_ID_HYPER_TIMECOP,
    SPRITE_TYPE_REGULAR_ENEMY, 0x00, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_3, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_UP_DOWN, 0x20, 0x00, DIM_SPRITE_ID_HYPER_TIMECOP,
    SPRITE_TYPE_REGULAR_ENEMY, 0x00, SPRITE_SIZE_16PX_16PX | SPRITE_PALETTE_3, SPRITE_ANIMATION_FULL, SPRITE_MOVEMENT_RANDOM_WANDER, 0x20, 0x00, DIM_SPRITE_ID_HYPER_TIMECOP
};

